// Top 200 NHL pool draft picks, in draft order (as of 2026-09-30).
export type Position = "F" | "D" | "G";

export type PlayerNote = "injured" | "suspended" | "rookie";

export type PoolPick = {
  rank: number;
  name: string;
  position: Position;
  team: string;
  note?: PlayerNote;
};

export const nhlPoolRankings: PoolPick[] = [
  { rank: 1, name: "Connor McDavid", position: "F", team: "EDM" },
  { rank: 2, name: "Nathan MacKinnon", position: "F", team: "COL" },
  { rank: 3, name: "Nikita Kucherov", position: "F", team: "TBL" },
  { rank: 4, name: "Macklin Celebrini", position: "F", team: "SJS" },
  { rank: 5, name: "Leon Draisaitl", position: "F", team: "EDM" },
  { rank: 6, name: "David Pastrnak", position: "F", team: "BOS" },
  { rank: 7, name: "Cale Makar", position: "D", team: "COL" },
  { rank: 8, name: "Kirill Kaprizov", position: "F", team: "MIN" },
  { rank: 9, name: "Jason Robertson", position: "F", team: "DAL" },
  { rank: 10, name: "Evan Bouchard", position: "D", team: "EDM" },
  { rank: 11, name: "Andrei Vasilevskiy", position: "G", team: "TBL" },
  { rank: 12, name: "Quinn Hughes", position: "D", team: "MIN" },
  { rank: 13, name: "Matt Boldy", position: "F", team: "MIN" },
  { rank: 14, name: "Wyatt Johnston", position: "F", team: "DAL" },
  { rank: 15, name: "Zach Werenski", position: "D", team: "CBJ" },
  { rank: 16, name: "Nick Suzuki", position: "F", team: "MTL" },
  { rank: 17, name: "Auston Matthews", position: "F", team: "TOR" },
  { rank: 18, name: "Jack Hughes", position: "F", team: "NJD" },
  { rank: 19, name: "Jack Eichel", position: "F", team: "VGK" },
  { rank: 20, name: "Cole Caufield", position: "F", team: "MTL" },
  { rank: 21, name: "Brady Tkachuk", position: "F", team: "FLA" },
  { rank: 22, name: "Martin Necas", position: "F", team: "COL" },
  { rank: 23, name: "Mikko Rantanen", position: "F", team: "DAL" },
  { rank: 24, name: "Matthew Tkachuk", position: "F", team: "FLA" },
  { rank: 25, name: "Lane Hutson", position: "D", team: "MTL" },
  { rank: 26, name: "Logan Thompson", position: "G", team: "WSH" },
  { rank: 27, name: "Ilya Sorokin", position: "G", team: "NYI" },
  { rank: 28, name: "Jake Oettinger", position: "G", team: "DAL" },
  { rank: 29, name: "Rasmus Dahlin", position: "D", team: "BUF" },
  { rank: 30, name: "Kyle Connor", position: "F", team: "WPG" },
  { rank: 31, name: "Tage Thompson", position: "F", team: "BUF" },
  { rank: 32, name: "Cutter Gauthier", position: "F", team: "ANA" },
  { rank: 33, name: "Dylan Guenther", position: "F", team: "UTA" },
  { rank: 34, name: "Jake Guentzel", position: "F", team: "TBL" },
  { rank: 35, name: "William Nylander", position: "F", team: "TOR" },
  { rank: 36, name: "Sam Reinhart", position: "F", team: "FLA" },
  { rank: 37, name: "Filip Forsberg", position: "F", team: "NSH" },
  { rank: 38, name: "Matthew Schaefer", position: "D", team: "NYI" },
  { rank: 39, name: "Igor Shesterkin", position: "G", team: "NYR" },
  { rank: 40, name: "Connor Hellebuyck", position: "G", team: "WPG", note: "suspended" },
  { rank: 41, name: "Mark Scheifele", position: "F", team: "WPG" },
  { rank: 42, name: "Leo Carlsson", position: "F", team: "ANA" },
  { rank: 43, name: "Brandon Hagel", position: "F", team: "TBL" },
  { rank: 44, name: "Alex DeBrincat", position: "F", team: "DET" },
  { rank: 45, name: "Moritz Seider", position: "D", team: "DET" },
  { rank: 46, name: "Clayton Keller", position: "F", team: "UTA" },
  { rank: 47, name: "Sidney Crosby", position: "F", team: "PIT" },
  { rank: 48, name: "Aleksander Barkov", position: "F", team: "FLA" },
  { rank: 49, name: "Tim Stützle", position: "F", team: "OTT" },
  { rank: 50, name: "Juraj Slafkovsky", position: "F", team: "MTL" },
  { rank: 51, name: "Artemi Panarin", position: "F", team: "LAK" },
  { rank: 52, name: "Adrian Kempe", position: "F", team: "LAK" },
  { rank: 53, name: "Scott Wedgewood", position: "G", team: "COL" },
  { rank: 54, name: "Jesper Wallstedt", position: "G", team: "MIN" },
  { rank: 55, name: "Darren Raddysh", position: "D", team: "TOR" },
  { rank: 56, name: "Jakob Chychrun", position: "D", team: "WSH" },
  { rank: 57, name: "Jake Sanderson", position: "D", team: "OTT" },
  { rank: 58, name: "Mitch Marner", position: "F", team: "VGK" },
  { rank: 59, name: "Kirill Marchenko", position: "F", team: "TOR" },
  { rank: 60, name: "Robert Thomas", position: "F", team: "STL" },
  { rank: 61, name: "Dylan Holloway", position: "F", team: "STL" },
  { rank: 62, name: "Will Smith", position: "F", team: "SJS" },
  { rank: 63, name: "Brayden Point", position: "F", team: "TBL" },
  { rank: 64, name: "Jeremy Swayman", position: "G", team: "BOS" },
  { rank: 65, name: "Connor Bedard", position: "F", team: "CHI", note: "injured" },
  { rank: 66, name: "Mika Zibanejad", position: "F", team: "NYR" },
  { rank: 67, name: "Nico Hischier", position: "F", team: "NJD" },
  { rank: 68, name: "Bo Horvat", position: "F", team: "NYI" },
  { rank: 69, name: "Sebastian Aho", position: "F", team: "CAR" },
  { rank: 70, name: "Adam Fantilli", position: "F", team: "CBJ" },
  { rank: 71, name: "Pavel Dorofeyev", position: "F", team: "NYR" },
  { rank: 72, name: "Drake Batherson", position: "F", team: "OTT" },
  { rank: 73, name: "Porter Martone", position: "F", team: "PHI", note: "rookie" },
  { rank: 74, name: "Adam Fox", position: "D", team: "NYR" },
  { rank: 75, name: "Brandon Bussi", position: "G", team: "CAR" },
  { rank: 76, name: "Jacob Markstrom", position: "G", team: "FLA" },
  { rank: 77, name: "Miro Heiskanen", position: "D", team: "DAL" },
  { rank: 78, name: "Lucas Raymond", position: "F", team: "DET" },
  { rank: 79, name: "Jesper Bratt", position: "F", team: "NJD" },
  { rank: 80, name: "Logan Cooley", position: "F", team: "UTA" },
  { rank: 81, name: "Beckett Sennecke", position: "F", team: "ANA" },
  { rank: 82, name: "Tom Wilson", position: "F", team: "WSH" },
  { rank: 83, name: "Dylan Larkin", position: "F", team: "DET", note: "injured" },
  { rank: 84, name: "John Tavares", position: "F", team: "TOR" },
  { rank: 85, name: "J.T. Miller", position: "F", team: "NYR" },
  { rank: 86, name: "Timo Meier", position: "F", team: "NJD" },
  { rank: 87, name: "Andrei Svechnikov", position: "F", team: "CAR" },
  { rank: 88, name: "Zach Hyman", position: "F", team: "EDM" },
  { rank: 89, name: "Roope Hintz", position: "F", team: "DAL" },
  { rank: 90, name: "Ivan Demidov", position: "F", team: "MTL" },
  { rank: 91, name: "Jackson LaCombe", position: "D", team: "ANA" },
  { rank: 92, name: "Erik Karlsson", position: "D", team: "PIT" },
  { rank: 93, name: "Jakub Dobes", position: "G", team: "MTL" },
  { rank: 94, name: "Karel Vejmelka", position: "G", team: "UTA" },
  { rank: 95, name: "Roman Josi", position: "D", team: "NSH" },
  { rank: 96, name: "John Carlson", position: "D", team: "TBL" },
  { rank: 97, name: "Jimmy Snuggerud", position: "F", team: "STL" },
  { rank: 98, name: "Alex Ovechkin", position: "F", team: "WSH" },
  { rank: 99, name: "Gavin McKenna", position: "F", team: "TOR", note: "rookie" },
  { rank: 100, name: "Nick Schmaltz", position: "F", team: "UTA" },
  { rank: 101, name: "Steven Stamkos", position: "F", team: "NSH" },
  { rank: 102, name: "Rickard Rakell", position: "F", team: "PIT" },
  { rank: 103, name: "Travis Konecny", position: "F", team: "PHI" },
  { rank: 104, name: "Mark Stone", position: "F", team: "VGK" },
  { rank: 105, name: "Ivar Stenberg", position: "F", team: "SJS", note: "rookie" },
  { rank: 106, name: "Nikolaj Ehlers", position: "F", team: "CAR" },
  { rank: 107, name: "Bryan Rust", position: "F", team: "PIT", note: "injured" },
  { rank: 108, name: "Alex Tuch", position: "F", team: "WSH" },
  { rank: 109, name: "Morgan Geekie", position: "F", team: "BOS" },
  { rank: 110, name: "Quinton Byfield", position: "F", team: "LAK" },
  { rank: 111, name: "Nazem Kadri", position: "F", team: "COL" },
  { rank: 112, name: "Sam Bennett", position: "F", team: "FLA" },
  { rank: 113, name: "Mikhail Sergachev", position: "D", team: "UTA" },
  { rank: 114, name: "Charlie McAvoy", position: "D", team: "BOS", note: "suspended" },
  { rank: 115, name: "Mackenzie Blackwood", position: "G", team: "COL" },
  { rank: 116, name: "Sergei Bobrovsky", position: "G", team: "TOR" },
  { rank: 117, name: "Cole Hutson", position: "D", team: "WSH", note: "rookie" },
  { rank: 118, name: "Victor Hedman", position: "D", team: "TBL" },
  { rank: 119, name: "Shayne Gostisbehere", position: "D", team: "CAR" },
  { rank: 120, name: "Dylan Strome", position: "F", team: "WSH" },
  { rank: 121, name: "Brock Nelson", position: "F", team: "COL" },
  { rank: 122, name: "Dylan Cozens", position: "F", team: "OTT" },
  { rank: 123, name: "Joel Eriksson Ek", position: "F", team: "MIN" },
  { rank: 124, name: "Anton Frondell", position: "F", team: "CHI", note: "rookie" },
  { rank: 125, name: "Vincent Trocheck", position: "F", team: "UTA" },
  { rank: 126, name: "Ryan O'Reilly", position: "F", team: "NSH" },
  { rank: 127, name: "Matthew Knies", position: "F", team: "CBJ" },
  { rank: 128, name: "Jordan Kyrou", position: "F", team: "WSH" },
  { rank: 129, name: "Logan Stankoven", position: "F", team: "CAR" },
  { rank: 130, name: "Jackson Blake", position: "F", team: "CAR" },
  { rank: 131, name: "Trevor Zegras", position: "F", team: "PHI" },
  { rank: 132, name: "Evgeni Malkin", position: "F", team: "PIT" },
  { rank: 133, name: "Patrick Kane", position: "F", team: "CHI" },
  { rank: 134, name: "Josh Doan", position: "F", team: "BUF" },
  { rank: 135, name: "Mathew Barzal", position: "F", team: "NYI", note: "injured" },
  { rank: 136, name: "Ryan Nugent-Hopkins", position: "F", team: "EDM", note: "injured" },
  { rank: 137, name: "Carter Verhaeghe", position: "F", team: "FLA" },
  { rank: 138, name: "Mikael Granlund", position: "F", team: "ANA" },
  { rank: 139, name: "Elias Pettersson", position: "F", team: "VAN" },
  { rank: 140, name: "Gabriel Vilardi", position: "F", team: "WPG" },
  { rank: 141, name: "William Eklund", position: "F", team: "OTT" },
  { rank: 142, name: "Alexis Lafreniere", position: "F", team: "NYR" },
  { rank: 143, name: "Owen Tippett", position: "F", team: "PHI" },
  { rank: 144, name: "Pavel Zacha", position: "F", team: "BOS" },
  { rank: 145, name: "Ukko-Pekka Luukkonen", position: "G", team: "BUF" },
  { rank: 146, name: "Linus Ullmark", position: "G", team: "OTT" },
  { rank: 147, name: "Carter Hart", position: "G", team: "VGK" },
  { rank: 148, name: "Brandt Clarke", position: "D", team: "LAK" },
  { rank: 149, name: "Noah Dobson", position: "D", team: "MTL" },
  { rank: 150, name: "Josh Morrissey", position: "D", team: "WPG" },
  { rank: 151, name: "Dougie Hamilton", position: "D", team: "NJD" },
  { rank: 152, name: "Mason Marchment", position: "F", team: "SJS" },
  { rank: 153, name: "JJ Peterka", position: "F", team: "BOS" },
  { rank: 154, name: "Gabriel Landeskog", position: "F", team: "COL" },
  { rank: 155, name: "Frank Nazar", position: "F", team: "CHI" },
  { rank: 156, name: "Egor Chinakhov", position: "F", team: "PIT" },
  { rank: 157, name: "Luke Evangelista", position: "F", team: "NJD" },
  { rank: 158, name: "Ryan Leonard", position: "F", team: "WSH" },
  { rank: 159, name: "Anthony Mantha", position: "F", team: "NJD" },
  { rank: 160, name: "Gabe Perreault", position: "F", team: "NYR" },
  { rank: 161, name: "Michael Misa", position: "F", team: "SJS" },
  { rank: 162, name: "Igor Chernyshov", position: "F", team: "SJS" },
  { rank: 163, name: "Joel Hofer", position: "G", team: "STL" },
  { rank: 164, name: "Dan Vladar", position: "G", team: "PHI" },
  { rank: 165, name: "Shea Theodore", position: "D", team: "VGK" },
  { rank: 166, name: "Bowen Byram", position: "D", team: "CHI" },
  { rank: 167, name: "MacKenzie Weegar", position: "D", team: "UTA" },
  { rank: 168, name: "Brandon Montour", position: "D", team: "SEA" },
  { rank: 169, name: "Spencer Knight", position: "G", team: "CHI" },
  { rank: 170, name: "Jet Greaves", position: "G", team: "CBJ" },
  { rank: 171, name: "Juuse Saros", position: "G", team: "NSH" },
  { rank: 172, name: "Filip Hronek", position: "D", team: "VAN" },
  { rank: 173, name: "Seth Jones", position: "D", team: "FLA" },
  { rank: 174, name: "Tomas Hertl", position: "F", team: "VGK" },
  { rank: 175, name: "Blake Coleman", position: "F", team: "MIN" },
  { rank: 176, name: "Ryan Hartman", position: "F", team: "MIN" },
  { rank: 177, name: "Mats Zuccarello", position: "F", team: "LAK" },
  { rank: 178, name: "Valeri Nichushkin", position: "F", team: "CBJ" },
  { rank: 179, name: "Roman Kantserov", position: "F", team: "CHI", note: "rookie" },
  { rank: 180, name: "Marco Rossi", position: "F", team: "VAN" },
  { rank: 181, name: "Anthony Cirelli", position: "F", team: "TBL" },
  { rank: 182, name: "Matt Duchene", position: "F", team: "DAL" },
  { rank: 183, name: "Jake DeBrusk", position: "F", team: "VAN" },
  { rank: 184, name: "Brock Boeser", position: "F", team: "VAN" },
  { rank: 185, name: "Chris Kreider", position: "F", team: "MTL" },
  { rank: 186, name: "Zach Benson", position: "F", team: "BUF" },
  { rank: 187, name: "Tyson Foerster", position: "F", team: "PHI" },
  { rank: 188, name: "Konsta Helenius", position: "F", team: "BUF", note: "rookie" },
  { rank: 189, name: "James Hagens", position: "F", team: "BOS", note: "rookie" },
  { rank: 190, name: "Collin Graf", position: "F", team: "SJS" },
  { rank: 191, name: "Mason McTavish", position: "F", team: "STL" },
  { rank: 192, name: "Tyler Bertuzzi", position: "F", team: "CHI" },
  { rank: 193, name: "Fraser Minten", position: "F", team: "BOS" },
  { rank: 194, name: "Vince Dunn", position: "D", team: "SEA" },
  { rank: 195, name: "Thomas Harley", position: "D", team: "DAL" },
  { rank: 196, name: "Philip Broberg", position: "D", team: "STL" },
  { rank: 197, name: "Rasmus Andersson", position: "D", team: "VGK" },
  { rank: 198, name: "Yaroslav Askarov", position: "G", team: "SJS" },
  { rank: 199, name: "Lukas Dostal", position: "G", team: "ANA" },
  { rank: 200, name: "Vasily Podkolzin", position: "F", team: "EDM" },
];
